# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DataMsg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DataMsg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MeterSummaryData_pb2 as MeterSummaryData__pb2
import HemsStreamMessage_pb2 as HemsStreamMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rDataMsg.proto\x1a\x16MeterSummaryData.proto\x1a\x17HemsStreamMessage.proto\"\xbe\x02\n\x07\x44\x61taMsg\x12\x14\n\x0cprotocol_ver\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12!\n\x06meters\x18\x03 \x01(\x0b\x32\x11.MeterSummaryData\x12\x1c\n\tbatt_mode\x18\x04 \x01(\x0e\x32\t.BattMode\x12\x12\n\nbackup_soc\x18\x05 \x01(\x05\x12\x33\n\x18\x64ry_contact_relay_status\x18\x06 \x03(\x0b\x32\x11.DryContactStatus\x12/\n\x16\x64ry_contact_relay_name\x18\x07 \x03(\x0b\x32\x0f.DryContactName\x12 \n\x0bload_status\x18\x08 \x03(\x0b\x32\x0b.LoadStatus\x12-\n\x12power_match_status\x18\t \x01(\x0b\x32\x11.PowerMatchStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataMsg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAMSG']._serialized_start=67
  _globals['_DATAMSG']._serialized_end=385
# @@protoc_insertion_point(module_scope)
